# MinimalOS – ZSH Configuration
# ─────────────────────────────────────────────────────────────────────────────

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS HIST_IGNORE_SPACE SHARE_HISTORY

# Options
setopt AUTO_CD
setopt CORRECT
setopt NO_BEEP

# Completion
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Prompt — minimal, cwal-aware
autoload -Uz colors && colors
PROMPT='%F{blue}%~%f %F{green}›%f '
RPROMPT='%F{240}%*%f'

# Plugins (installed by pacman)
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Cargo / Rust
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# PATH — user bin
export PATH="$HOME/.local/bin:$PATH"

# MinimalOS config
export MINIMALOS_CONF="/etc/minimalos/minimalos.conf"

# Default editor
export EDITOR="nvim"
export VISUAL="nvim"

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lah --color=auto'
alias la='ls -A --color=auto'
alias grep='grep --color=auto'
alias vim='nvim'
alias vi='nvim'
alias br='broot'
alias update='SOS_UpdateBase.sh'

# Broot launcher integration (generated by broot on first run)
[ -f "$HOME/.config/broot/launcher/bash/br" ] && \
    source "$HOME/.config/broot/launcher/bash/br"
