[general]
backend = imagemagick

[options]
saturation = 1.0
contrast = 0

# After generating colors, write templates to their destinations.
# Syntax: template_name = /destination/path | optional_reload_command
[links]
colors-alacritty.toml = ~/.cache/cwal/colors-alacritty.toml
colors-sway.conf = ~/.config/sway/colors.conf | swaymsg reload
